export const QueryKeys = {
  getAllInquiry: "getAllInquiry",
  getKidRecord: "getKidRecord",
  getStudentRecord: "getStudentRecord",
  getAllAdmission: "getAllAdmission",
  getAdmission: "getAdmission",
  getKidAdmissionRecord: "getKidAdmissionRecord",
  getAllCourse: "getAllCourse",
  getAllInquiryType: "getAllInquiryType",
  getAllCompletedCourse: "getAllCompletedCourse",
  getInquiry: "getInquiry",
  all_CastCategory: "all_CastCategory",
  getAdmissionQuota: "getAdmissionQuota",
  ALL_ADMISSION_QUOTA: "ALL_ADMISSION_QUOTA",
  ALL_CAST_CATEGORY: "ALL_CAST_CATEGORY",
  ALL_COURSE: "ALL_COURSE",
  ALL_DOCUMENT: "ALL_DOCUMENT",
  ALL_FEES: "ALL_FEES",
  ALL_INQUIRY_TYPE: "ALL_INQUIRY_TYPE",
  getCompleredCourse : 'getCompleredCourse',
  getAdmissionCourse: 'getAdmissionCourse',
  getAllFeesType : 'getAllFeesType',
  getFeesType : 'getFeesType',
  getAllDocumentType : 'getAllDocumentType'
};
